baseurl = "http://www.example.com"
title = "Home"
theme = 'ananke'
languagecode = "en"
defaultcontentlanguage = "en"

params:
  ananke_socials:
  - name: twitter
    url: https://twitter.com/theNewDynamic
  - name: github
    url: https://github.com/